[build]
  # Publicamos la raíz
  publish = "."
  # Generamos el sitemap automáticamente antes de cada despliegue
  command = "node scripts/generate-sitemap.mjs"

[[redirects]]
  from = "/servicios/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/electricista-en/*"
  to = "/"
  status = 301
